name: CI

permissions: {}

defaults:
  run:
    shell: bash

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  betterleaks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: ./.github/actions/setup
      - run: betterleaks git
